Switch to nested dict update to please mypy
mypy recently started giving:

error: No overload variant of "update" of "MutableMapping" matches argument types "dict[str, str]", "dict[str, str]"  [call-overload]

(note that the code was working fine...)